### ISSUE TITLE
Release pipeline does not depend on tests

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/python-copier-template#241]
[The CI dependencies](https://github.com/DiamondLightSource/python-copier-template/blob/main/template/%7B%25%20if%20git_platform%3D%3D%22github.com%22%20%25%7D.github%7B%25%20endif%20%25%7D/workflows/ci.yml.jinja) as they are mean that Github will try to push to PyPi and GHCR on a tag even if the tests fail. We have seen this cause problems in production where uncaught issues make into supposedly "safe" releases. This is especially important for containers.

## Acceptance Criteria
- When a tag is pushed, the tests are run (already happens)
- If those tests fail, the PyPi upload job is not triggered
- If those tests fail, the container build job is not triggered

**Comment by AlexanderWells-diamond** [comment]
Is there a use in building the container, but not publishing it, even if the tests fail?

**Comment by coretl** [comment]
Hmm, practicality vs purity... I explicitly did not put testing as a requirement for publish because:
- Main should always be passing tests anyway
- When you tag main it should release as soon as possible
- If you have a flaky test it is annoying that it blocks your release when it passed on main

Were the problems you mention caused by releasing from a branch, or was main broken when it was released?

**Comment by callumforrester** [comment]
@AlexanderWells-diamond I was actually considering opening a separate issue about that since it's also a problem we've seen. We had some confusion recently where a [project was released but the PyPi upload failed](https://github.com/DiamondLightSource/blueapi/actions/runs/13590661513/attempts/1). If the container exists in GHCR but the project doesn't exist on PyPi (or vice versa) it can be confusing to users/new team members, which is why I'd favour an all-or-nothing approach (or as close as we can practically get), thoughts welcome.

@coretl In the same incident we saw [a dependency update breaking `main` between most recent merge and release](https://github.com/DiamondLightSource/blueapi/actions/runs/13590661513). Arguably this is solved with [dependency locking](https://diamondlightsource.github.io/python-copier-template/main/how-to/lock-requirements.html), but not for all projects. Also a lockfile only matters in building a container/dev environment.

Tagging @olliesilvester and @DominicOram in case they have opinions, since they were also part of the incident linked (and since they `pip install blueapi` in their production environment).

**Comment by olliesilvester** [comment]
In general I agree with this acceptance criteria, but as Tom said it would be very annoying for flaky unit tests preventing us from releasing.

Would be good if, on a release with failed CI, you still have the option to 'ignore and release anyway'.

**Comment by DominicOram** [comment]
You should be able to just retrigger the CI if the issue is a flaky test, right? I think I would rather the certainty in the release and that mean that it sometimes holds releases up on flaky tests. Flaky tests happen but we should be trying to fix them rather than building process to work around them

**Comment by coretl** [comment]
Hmm, still on the fence, but looks like the majority agrees with release depending on tests, so happy to accept a PR for that

**Comment by callumforrester** [comment]
Added to core backlog, thanks
